### ISSUE TITLE
User can view app homepage

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/ajax-project#1]
## Plan

Create a responsive webpage for users to navigate between the servant lists and damage calculator.

## wireframe
![image](https://user-images.githubusercontent.com/8008839/98749274-22145800-2370-11eb-8956-5db0d7c075b3.png)

## Tasks List:
- [x] Create a header
- [x] Use an image for the background
- [x] Create a button that navigates the user to the servant lists
- [x] Create a button that navigates the user to the NP damage calculator
