### ISSUE TITLE
User can create new list

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/ajax-project#2]
## Plan
Create a separate view where the user can make a new list.

## Wireframe
![image](https://user-images.githubusercontent.com/8008839/98749991-bcc16680-2371-11eb-81f9-024b272887b8.png)

![image](https://user-images.githubusercontent.com/8008839/98750016-c945bf00-2371-11eb-92e4-1ff00388df74.png)

## Tasks List:
- [x] Create a background
- [x] Create a button that makes a modal appear
    - [x] Add an input field to the modal
    - [x] Setup localStorage
    - [x] Create a button on the modal that creates a list that uses the value entered in the input field
- [x] Show all lists
    - [x] Each list has a view button that navigates the user to a new view that displays the names of servants in the list
    - [x] Each list has a delete button that removes the list
- [x] Save the information to localstorage
- [x] Make a menu bar
    - [x] Create a menu button
    - [x] create a back button that navigates the back to homepage
