### ISSUE TITLE
User can add characters to the list

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/ajax-project#3]
## Plan
Allow the user to add characters to the list

## Wireframe
![image](https://user-images.githubusercontent.com/8008839/98751130-5ab63080-2374-11eb-9d8e-724e77389e1a.png)

![image](https://user-images.githubusercontent.com/8008839/98751156-699ce300-2374-11eb-91c7-2833c66d4936.png)

## Tasks List
- [x] Create a button that inserts a new character to the list
    - [x] on click, a modal appears
    - [x] Modal has a text input and radio button 
    - [x] Create a submit button for the modal
       - [x] Create a modal that displays a list of matching result for the user to choose from
- [x] Display all characters name in the list
    - [x] Each name has a view and delete button
- [x] Create a button that navigates to the view containing the material table
