### ISSUE TITLE
User can edit the characters information on the list

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/ajax-project#5]
## Plan
Create a responsive view page to display the selected character information

## Wireframe
![image](https://user-images.githubusercontent.com/8008839/99375123-35e02280-2878-11eb-80f7-ad00e9fb3fb7.png)
![image](https://user-images.githubusercontent.com/8008839/99375195-4abcb600-2878-11eb-8ac1-38ff86f91fec.png)

## Task List
- [x] Create the page layout
  - [x] Display the information about the servant
- [x] Create an edit button
  - [x] On click a modal appears
    - [x] Modal has input fields for user to enter new data
    - [x] On submit, update the servant data stored in the localStorage and update the information displayed
