### ISSUE TITLE
User can see the total amount of materials for skills and ascension for the entire list

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/ajax-project#6]
## Plan
Create a responsive webpage that displays the total amount of materials needed for characters on the list

## wireframe
![image](https://user-images.githubusercontent.com/8008839/98752337-db762c00-2376-11eb-9d40-5704a1481e0f.png)

## Tasks list
- [x] Make a request to the API to get the items information
- [x] Save the image URL and names of the item
- [ ] Create a table with 3 columns
  - [ ] First column displays the picture of the material
  - [ ] Second column contains the name of the material
  - [ ] Third column shows the total amount needed for all the servants on the list
- [ ] For each item, get the total amount that is required for all the servants on the list
- [ ] Display the information in the correct columns
